version: "3.8"
services:
  mongo:
    image: mongo
    container_name: starter_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    container_name: starter_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: starter_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - server

volumes:
  data:
